// SPDX-License-Identifier: Apache-2.0

// Generated by GenerateLifts — do not edit. Run `swift run GenerateLifts Sources/SwiftRex`.

import CoreFP
import DataStructure

// `PrismKeyPath` action spellings of the Middleware lift overloads. The Prism-action
// versions live in Middleware+Transforms; these recover the prism via `Prism(path)`.
extension Middleware {
    /// Lifts the action axis via a `PrismKeyPath`.
    public func liftAction<GlobalAction: Prismatic & Sendable>(
        _ path: PrismKeyPath<GlobalAction, Action>
    ) -> Middleware<GlobalAction, State, Environment> {
        liftAction(Prism(path))
    }

    /// Lifts all three axes — `PrismKeyPath` action, closure state, closure environment.
    public func lift<GA: Prismatic & Sendable, GS: Sendable, GE: Sendable>(
        action path: PrismKeyPath<GA, Action>,
        state f: @escaping @Sendable (GS) -> State,
        environment g: @escaping @Sendable (GE) -> Environment
    ) -> Middleware<GA, GS, GE> {
        lift(action: Prism(path), state: f, environment: g)
    }

    /// Lifts all three axes — `PrismKeyPath` action, `Lens` state, closure environment.
    public func lift<GA: Prismatic & Sendable, GS: Sendable, GE: Sendable>(
        action path: PrismKeyPath<GA, Action>,
        state lens: Lens<GS, State>,
        environment g: @escaping @Sendable (GE) -> Environment
    ) -> Middleware<GA, GS, GE> {
        lift(action: Prism(path), state: lens, environment: g)
    }

    /// Lifts all three axes — `PrismKeyPath` action, `Prism` state, closure environment.
    public func lift<GA: Prismatic & Sendable, GS: Sendable, GE: Sendable>(
        action path: PrismKeyPath<GA, Action>,
        state statePrism: Prism<GS, State>,
        environment g: @escaping @Sendable (GE) -> Environment
    ) -> Middleware<GA, GS, GE> {
        lift(action: Prism(path), state: statePrism, environment: g)
    }

    /// Lifts all three axes — `PrismKeyPath` action, `AffineTraversal` state, closure environment.
    public func lift<GA: Prismatic & Sendable, GS: Sendable, GE: Sendable>(
        action path: PrismKeyPath<GA, Action>,
        state traversal: AffineTraversal<GS, State>,
        environment g: @escaping @Sendable (GE) -> Environment
    ) -> Middleware<GA, GS, GE> {
        lift(action: Prism(path), state: traversal, environment: g)
    }
}
