// SPDX-License-Identifier: Apache-2.0

// Generated by GenerateLifts — do not edit. Run `swift run GenerateLifts Sources/SwiftRex`.

import CoreFP
import DataStructure

// Lifts a `Reducer<ActionType, StateType>` into a parent action/state, across every
// combination of action and state optics (closure, Prism, AffineTraversal, Lens,
// WritableKeyPath, PrismKeyPath, AffineKeyPath). The reducer is a no-op for unmatched
// actions or absent state foci.
extension Reducer {
    /// Lifts the action axis via a getter closure, and the state axis via getter/setter closures.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        actionGetter: @escaping @Sendable (GlobalAction) -> ActionType?,
        stateGetter: @escaping @Sendable (GlobalState) -> StateType,
        stateSetter: @escaping @Sendable (inout GlobalState, StateType) -> Void
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionGetter(globalAction) else { return .identity }
            return Lens(get: stateGetter, setMut: stateSetter).lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via a getter closure.
    public func lift<GlobalAction: Sendable>(
        actionGetter: @escaping @Sendable (GlobalAction) -> ActionType?
    ) -> Reducer<GlobalAction, StateType> {
        .reduce { globalAction in
            guard let localAction = actionGetter(globalAction) else { return .identity }
            return self.reduce(localAction)
        }
    }

    /// Lifts the state axis via getter/setter closures.
    public func lift<GlobalState: Sendable>(
        stateGetter: @escaping @Sendable (GlobalState) -> StateType,
        stateSetter: @escaping @Sendable (inout GlobalState, StateType) -> Void
    ) -> Reducer<ActionType, GlobalState> {
        .reduce { action in Lens(get: stateGetter, setMut: stateSetter).lift(self.reduce(action)) }
    }

    /// Lifts the state axis via a `WritableKeyPath`.
    public func lift<GlobalState: Sendable>(
        state keyPath: WritableKeyPath<GlobalState, StateType>
    ) -> Reducer<ActionType, GlobalState> {
        .reduce { action in EndoMut { globalState in self.reduce(action)(&globalState[keyPath: keyPath]) } }
    }

    /// Lifts the state axis via a `Lens`.
    public func lift<GlobalState: Sendable>(
        state lens: Lens<GlobalState, StateType>
    ) -> Reducer<ActionType, GlobalState> {
        .reduce { action in lens.lift(self.reduce(action)) }
    }

    /// Lifts the state axis via a `Prism`.
    public func lift<GlobalState: Sendable>(
        state statePrism: Prism<GlobalState, StateType>
    ) -> Reducer<ActionType, GlobalState> {
        .reduce { action in statePrism.lift(self.reduce(action)) }
    }

    /// Lifts the state axis via an `AffineTraversal`.
    public func lift<GlobalState: Sendable>(
        state stateTraversal: AffineTraversal<GlobalState, StateType>
    ) -> Reducer<ActionType, GlobalState> {
        .reduce { action in stateTraversal.lift(self.reduce(action)) }
    }

    /// Lifts the action axis via a `Prism`.
    public func lift<GlobalAction: Sendable>(
        action actionPrism: Prism<GlobalAction, ActionType>
    ) -> Reducer<GlobalAction, StateType> {
        .reduce { globalAction in
            guard let localAction = actionPrism.preview(globalAction) else { return .identity }
            return self.reduce(localAction)
        }
    }

    /// Lifts the action axis via a `Prism`, and the state axis via a `WritableKeyPath`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionPrism: Prism<GlobalAction, ActionType>,
        state keyPath: WritableKeyPath<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionPrism.preview(globalAction) else { return .identity }
            return EndoMut { globalState in self.reduce(localAction)(&globalState[keyPath: keyPath]) }
        }
    }

    /// Lifts the action axis via a `Prism`, and the state axis via a `Lens`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionPrism: Prism<GlobalAction, ActionType>,
        state lens: Lens<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionPrism.preview(globalAction) else { return .identity }
            return lens.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via a `Prism`, and the state axis via a `Prism`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionPrism: Prism<GlobalAction, ActionType>,
        state statePrism: Prism<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionPrism.preview(globalAction) else { return .identity }
            return statePrism.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via a `Prism`, and the state axis via an `AffineTraversal`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionPrism: Prism<GlobalAction, ActionType>,
        state stateTraversal: AffineTraversal<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionPrism.preview(globalAction) else { return .identity }
            return stateTraversal.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via an `AffineTraversal`.
    public func lift<GlobalAction: Sendable>(
        action actionTraversal: AffineTraversal<GlobalAction, ActionType>
    ) -> Reducer<GlobalAction, StateType> {
        .reduce { globalAction in
            guard let localAction = actionTraversal.preview(globalAction) else { return .identity }
            return self.reduce(localAction)
        }
    }

    /// Lifts the action axis via an `AffineTraversal`, and the state axis via a `WritableKeyPath`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionTraversal: AffineTraversal<GlobalAction, ActionType>,
        state keyPath: WritableKeyPath<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionTraversal.preview(globalAction) else { return .identity }
            return EndoMut { globalState in self.reduce(localAction)(&globalState[keyPath: keyPath]) }
        }
    }

    /// Lifts the action axis via an `AffineTraversal`, and the state axis via a `Lens`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionTraversal: AffineTraversal<GlobalAction, ActionType>,
        state lens: Lens<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionTraversal.preview(globalAction) else { return .identity }
            return lens.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via an `AffineTraversal`, and the state axis via a `Prism`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionTraversal: AffineTraversal<GlobalAction, ActionType>,
        state statePrism: Prism<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionTraversal.preview(globalAction) else { return .identity }
            return statePrism.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via an `AffineTraversal`, and the state axis via an `AffineTraversal`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action actionTraversal: AffineTraversal<GlobalAction, ActionType>,
        state stateTraversal: AffineTraversal<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        .reduce { globalAction in
            guard let localAction = actionTraversal.preview(globalAction) else { return .identity }
            return stateTraversal.lift(self.reduce(localAction))
        }
    }

    /// Lifts the action axis via a `PrismKeyPath`.
    public func lift<GlobalAction: Prismatic & Sendable>(
        action path: PrismKeyPath<GlobalAction, ActionType>
    ) -> Reducer<GlobalAction, StateType> {
        lift(action: Prism(path))
    }

    /// Lifts the action axis via a `PrismKeyPath`, and the state axis via a `WritableKeyPath`.
    public func lift<GlobalAction: Prismatic & Sendable, GlobalState: Sendable>(
        action path: PrismKeyPath<GlobalAction, ActionType>,
        state keyPath: WritableKeyPath<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: Prism(path), state: keyPath)
    }

    /// Lifts the action axis via a `PrismKeyPath`, and the state axis via a `Lens`.
    public func lift<GlobalAction: Prismatic & Sendable, GlobalState: Sendable>(
        action path: PrismKeyPath<GlobalAction, ActionType>,
        state lens: Lens<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: Prism(path), state: lens)
    }

    /// Lifts the action axis via a `PrismKeyPath`, and the state axis via a `Prism`.
    public func lift<GlobalAction: Prismatic & Sendable, GlobalState: Sendable>(
        action path: PrismKeyPath<GlobalAction, ActionType>,
        state statePrism: Prism<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: Prism(path), state: statePrism)
    }

    /// Lifts the action axis via a `PrismKeyPath`, and the state axis via an `AffineTraversal`.
    public func lift<GlobalAction: Prismatic & Sendable, GlobalState: Sendable>(
        action path: PrismKeyPath<GlobalAction, ActionType>,
        state stateTraversal: AffineTraversal<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: Prism(path), state: stateTraversal)
    }

    /// Lifts the action axis via an `AffineKeyPath`.
    public func lift<GlobalAction: Sendable>(
        action path: AffineKeyPath<GlobalAction, ActionType>
    ) -> Reducer<GlobalAction, StateType> {
        lift(action: AffineTraversal(path))
    }

    /// Lifts the action axis via an `AffineKeyPath`, and the state axis via a `WritableKeyPath`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action path: AffineKeyPath<GlobalAction, ActionType>,
        state keyPath: WritableKeyPath<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: AffineTraversal(path), state: keyPath)
    }

    /// Lifts the action axis via an `AffineKeyPath`, and the state axis via a `Lens`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action path: AffineKeyPath<GlobalAction, ActionType>,
        state lens: Lens<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: AffineTraversal(path), state: lens)
    }

    /// Lifts the action axis via an `AffineKeyPath`, and the state axis via a `Prism`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action path: AffineKeyPath<GlobalAction, ActionType>,
        state statePrism: Prism<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: AffineTraversal(path), state: statePrism)
    }

    /// Lifts the action axis via an `AffineKeyPath`, and the state axis via an `AffineTraversal`.
    public func lift<GlobalAction: Sendable, GlobalState: Sendable>(
        action path: AffineKeyPath<GlobalAction, ActionType>,
        state stateTraversal: AffineTraversal<GlobalState, StateType>
    ) -> Reducer<GlobalAction, GlobalState> {
        lift(action: AffineTraversal(path), state: stateTraversal)
    }
}
