version: 1
builder:
  configs:
    - platform: macosSpm
      documentation_targets:
        - SwiftRex
        - SwiftRexOperators
        - SwiftRexConcurrency
        - SwiftRexCombine
        - SwiftRexRxSwift
        - SwiftRexReactiveSwift
        - SwiftRexSwiftUI
    - platform: ios
    - platform: tvos
    - platform: watchos
    - platform: linux
