line_length:
  warning: 145
  error: 145
  ignores_comments: true
file_length:
  warning: 500
  error: 1000
type_body_length:
  warning: 300
  error: 350
function_parameter_count:
  warning: 6
  error: 8
nesting:
  type_level: 6
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - fn
    - v1
    - v2
type_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - Id
    - V1
    - V2
cyclomatic_complexity:
  warning: 12
  error: 14
disabled_rules:
  - force_try
  - force_cast
  - large_tuple
excluded:
  - Sources/SwiftRex/CodeGeneration
  - Pods
  - .build
  - DerivedData
opt_in_rules: # some rules are only opt-in
  - array_init
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  # - file_types_order
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_literal_brackets
  - multiline_parameters
  - no_extension_access_modifier
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_interface_builder
  # - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - sorted_imports
  - strong_iboutlet
  - toggle_bool
  # - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
custom_rules:
  double_space: # from https://github.com/IBM-Swift/Package-Builder
    include: "*.swift"
    name: "Double space"
    regex: '([a-z,A-Z] \s+)'
    message: "Double space between keywords"
    match_kinds: keyword
    severity: warning
  comments_space: # from https://github.com/brandenr/swiftlintconfig
    name: "Space After Comment"
    regex: '(^ *//\w+)'
    message: "There should be a space after //"
    severity: warning
  unnecessary_type: # from https://github.com/brandenr/swiftlintconfig
    name: "Unnecessary Type"
    regex: '[ a-zA-Z0-9]*(?:let|var) [ a-zA-Z0-9]*: ([a-zA-Z0-9]*)[ ]*= \1'
    message: "Type Definition Not Needed"
    severity: error