// SPDX-License-Identifier: Apache-2.0

#if canImport(Observation) && canImport(SwiftUI)
    import CoreFP
    @testable import SwiftRex
    @testable import SwiftRexArchitecture
    import SwiftUI
    import Testing

    // Proves the Feature protocol lets you abstract over a feature generically — driving BOTH its
    // behavior and its view without naming the concrete feature. The `@Feature` macro generates the
    // `: Feature` conformance (this one is view-bearing), inferred from the generated members.

    @Feature(strategy: .observationSimple)
    enum FPLeaf {
        struct State: Sendable, Equatable { var n = 0 }
        enum Action: Sendable, Equatable { case bump }
        struct Environment: Sendable { var step: Int }
        static func behavior() -> Behavior<Action, State, Environment> {
            .reduce { action, state in
                switch action {
                case .bump: state.n += 1
                }
            }
        }

        typealias Content = FPLeafView
    }

    @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
    @BoundTo(FPLeaf.self, strategy: .observationSimple)
    struct FPLeafView: View { var body: some View { Text("\(viewStore.state.n)") } }

    // `extension FPLeaf: Feature {}` is generated by @Feature — Body/Action/State/Environment inferred.

    // A generic that abstracts over ANY feature — driving both its behavior and its view through the
    // single Feature protocol, without naming the concrete feature inside.
    @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
    @MainActor
    private func drive<F: Feature>(_ feature: F.Type, store: any StoreType<F.Action, F.State>, environment: F.Environment) -> F.Body {
        _ = F.behavior()
        return F.view(store: store, environment: environment)
    }

    @Suite("Feature protocol")
    @MainActor
    struct FeatureProtocolTests {
        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func abstractsFeatureGenerically() {
            // Compiles ⇒ `drive` used a feature purely through the protocol (no concrete naming inside).
            let store = Store(initial: FPLeaf.State(), behavior: FPLeaf.behavior(), environment: FPLeaf.Environment(step: 1))
            _ = drive(FPLeaf.self, store: store, environment: FPLeaf.Environment(step: 1))
        }

        @Test func behaviorRunsThroughHasBehavior() {
            // The behavior half alone (HasBehavior) abstracts a feature's behavior — reusable for
            // logic-only features that have no view.
            func featureBehavior<F: HasBehavior>(_: F.Type) -> Behavior<F.Action, F.State, F.Environment> { F.behavior() }
            let store = Store(initial: FPLeaf.State(), behavior: featureBehavior(FPLeaf.self), environment: FPLeaf.Environment(step: 1))
            store.dispatch(.bump)
            #expect(store.state.n == 1)
        }
    }
#endif
