// SPDX-License-Identifier: Apache-2.0

#if canImport(Observation) && canImport(SwiftUI)
    import CoreFP
    @testable import SwiftRex
    @testable import SwiftRexArchitecture
    import SwiftUI
    import Testing

    // A child feature (a real @Feature so it conforms to `Feature`: behavior + view). Gateway derives
    // both its lifted behavior and its view from it.
    @Feature(strategy: .observationSimple)
    enum SCCounter {
        struct State: Sendable, Equatable { var count = 0 }
        enum Action: Sendable, Equatable { case inc, pull, add(Int) }
        struct Environment: Sendable { var step: Int }

        static func behavior() -> Behavior<Action, State, Environment> {
            .handle { action, _ in
                switch action {
                case .inc: .reduce { $0.count += 1 }
                case .pull: .produce { ctx in Effect.just(.add(ctx.environment.step)) } // reads env
                case let .add(n): .reduce { $0.count += n }
                }
            }
        }

        typealias Content = SCCounterView
    }

    @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
    @BoundTo(SCCounter.self, strategy: .observationSimple)
    struct SCCounterView: View { var body: some View { Text("\(viewStore.state.count)") } }

    // `extension SCCounter: Feature {}` is generated by @Feature.

    // @Prisms/@Lenses require >= fileprivate.
    // swiftlint:disable private_over_fileprivate
    @Prisms
    fileprivate enum SCAction: Sendable, Equatable {
        case counter(SCCounter.Action)
        case sheet(SCCounter.Action)
    }

    @Lenses
    fileprivate struct SCState: Sendable, Equatable {
        var counter = SCCounter.State()
        var sheet: SCCounter.State?
    }

    // swiftlint:enable private_over_fileprivate

    private struct SCWorld: Sendable {
        var step: Int = 10
        var counterEnv: SCCounter.Environment { .init(step: step) }
    }

    // The parent `Rig` — carries the app's (Action, State, Environment) triad; a `Gateway` relates it to
    // a child domain. `Action` is `SCAction` (Prismatic via @Prisms), as `Gateway` requires.
    private enum SCApp: FeatureDomain {
        typealias Action = SCAction
        typealias State = SCState
        typealias Environment = SCWorld
    }

    // A logic-only capability — `HasBehavior`, NO view (the shape of a system-event/capability package).
    // It is NOT a `Feature`; a `Gateway` over it lifts `.behavior` and, being view-less, has no `.view`.
    enum PingCapability {
        struct State: Sendable, Equatable { var pings = 0 }
        enum Action: Sendable, Equatable { case ping }
        struct Environment: Sendable { var by: Int }
        static func behavior() -> Behavior<Action, State, Environment> {
            .reduce { action, state in
                switch action {
                case .ping: state.pings += 1
                }
            }
        }
    }

    extension PingCapability: HasBehavior {}

    // @Prisms/@Lenses require >= fileprivate.
    // swiftlint:disable private_over_fileprivate
    @Prisms
    fileprivate enum PingGlobalAction: Sendable, Equatable { case ping(PingCapability.Action) }

    @Lenses
    fileprivate struct PingGlobalState: Sendable, Equatable { var ping = PingCapability.State() }
    // swiftlint:enable private_over_fileprivate

    private struct PingWorld: Sendable { var by: Int = 1 }

    private enum PingApp: FeatureDomain {
        typealias Action = PingGlobalAction
        typealias State = PingGlobalState
        typealias Environment = PingWorld
    }

    @Suite("Relay.Scope feature lift")
    @MainActor
    struct RelayScopeFeatureTests {
        // The scope literal is a compile-time proof of wiring — it wouldn't compile if the action case,
        // state slot, or env-narrowing didn't line up with SCCounter's own types. One declared scope drives
        // BOTH `.behavior(of:)` (the fold) and `.view(of:from:world:)` (the router).
        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func behaviorLiftsActionAndState() {
            let scope = Relay.Scope.identity
                .action(SCAction.prism.counter)
                .state(\SCState.counter)
                .environment { (_: SCWorld) in SCCounter.Environment(step: 0) }
            let store = Store(initial: SCState(), behavior: scope.behavior(of: SCCounter.self), environment: SCWorld())
            store.dispatch(.counter(.inc))
            #expect(store.state.counter.count == 1) // action prism + state key path both applied
        }

        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func envIsNarrowedFromWorld() async {
            let scope = Relay.Scope.identity
                .action(SCAction.prism.counter)
                .state(\SCState.counter)
                .environment { (w: SCWorld) in SCCounter.Environment(step: w.step) }
            let store = Store(initial: SCState(), behavior: scope.behavior(of: SCCounter.self), environment: SCWorld(step: 7))
            store.dispatch(.counter(.pull)) // effect reads env.step=7 → .add(7)
            await Task.yield()
            #expect(store.state.counter.count == 7)
        }

        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func envAsKeyPathConvenience() async {
            let scope = Relay.Scope.identity
                .action(SCAction.prism.counter)
                .state(\SCState.counter)
                .environment(\SCWorld.counterEnv)
            let store = Store(initial: SCState(), behavior: scope.behavior(of: SCCounter.self), environment: SCWorld(step: 3))
            store.dispatch(.counter(.pull))
            await Task.yield()
            #expect(store.state.counter.count == 3) // env-narrow via key path reached the effect
        }

        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func scopeBuildsTheChildView() {
            // One scope drives BOTH: `.behavior(of:)` (into the store) and `.view(of:from:world:)` here.
            let scope = Relay.Scope.identity
                .action(SCAction.prism.counter)
                .state(\SCState.counter)
                .environment { (_: SCWorld) in SCCounter.Environment(step: 0) }
            let store = Store(initial: SCState(), behavior: scope.behavior(of: SCCounter.self), environment: SCWorld())
            _ = scope.view(of: SCCounter.self, from: store, world: SCWorld())
        }

        @available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
        @Test func combineFoldsScopeBehaviors() {
            // Registration is just the behavior monoid — `Behavior.combine([...])` (or `<>`), no wrapper.
            let scope = Relay.Scope.identity
                .action(SCAction.prism.counter)
                .state(\SCState.counter)
                .environment { (_: SCWorld) in SCCounter.Environment(step: 0) }
            let app = Behavior.combine([scope.behavior(of: SCCounter.self)])
            let store = Store(initial: SCState(), behavior: app, environment: SCWorld())
            store.dispatch(.counter(.inc))
            #expect(store.state.counter.count == 1)
        }

        // A scope over a logic-only `HasBehavior` capability (no view) lifts `.behavior(of:)` just like a
        // full feature — the capability-package shape. `scope.view(of:…)` would NOT compile here, because
        // `PingCapability` is `HasBehavior` only and `view` lives on the `where …: ViewFactory` extension.
        @Test func scopeLiftsBehaviorOnlyCapability() {
            let scope = Relay.Scope.identity
                .action(PingGlobalAction.prism.ping)
                .state(\PingGlobalState.ping)
                .environment { (w: PingWorld) in PingCapability.Environment(by: w.by) }
            let store = Store(initial: PingGlobalState(), behavior: scope.behavior(of: PingCapability.self), environment: PingWorld())
            store.dispatch(.ping(.ping))
            #expect(store.state.ping.pings == 1) // behavior-only capability folded through the same scope
        }
    }
#endif
