#if canImport(Observation)
// Re-export FPMacros so @Prisms and @Lenses (generated by @Feature) are always in scope
// for any target that imports SwiftRexArchitecture.
@_exported import FPMacros

import SwiftRexSwiftUI

// MARK: - @Feature macro

/// Eliminates ``Feature`` protocol boilerplate from a feature enum.
///
/// Apply to an `enum` that serves as a feature namespace. The macro:
///
/// - Adds `Feature` protocol conformance via an extension
/// - Applies `@Prisms` to the nested `Action` enum (for ``TestStore`` `receive` assertions)
/// - Applies `@Lenses` to the nested `State` struct (for `liftState` ergonomics)
///
/// ```swift
/// @Feature
/// enum MoviesFeature {
///     struct State: Sendable { ... }         // @Lenses applied automatically
///     enum Action: Sendable { ... }          // @Prisms applied automatically
///     struct Environment: Sendable { ... }
///
///     @ViewModel final class ViewModel { ... }
///
///     static let mapState = ...
///     static let mapAction = ...
///     static func initialState() -> State { .init() }
///     static func behavior() -> Behavior<Action, State, Environment> { ... }
///
///     typealias Content = MovieListView      // still required — links feature to its view
/// }
/// ```
///
/// Because `@Feature` re-exports `FPMacros`, importing `SwiftRexArchitecture` is sufficient —
/// no explicit `import FPMacros` is needed in the file where `@Feature` is used.
@available(iOS 17, macOS 14, tvOS 17, watchOS 10, *)
@attached(memberAttribute)
@attached(extension, conformances: Feature)
public macro Feature() = #externalMacro(module: "SwiftRexMacros", type: "FeatureMacro")
#endif
