#!/bin/sh

SCRIPT_DIR=$(dirname "$0")
BOOTSTRAP="$SCRIPT_DIR/bootstrap"
CACHED_CARTFILE="Carthage/Cartfile.resolved"

if [ -e "$CACHED_CARTFILE" ]; then
    OUTDATED_DEPENDENCIES=$(scripts/cartfilediff "$CACHED_CARTFILE" Cartfile.resolved)

    if [ ! -z "$OUTDATED_DEPENDENCIES" ]
    then
        echo "Bootstrapping outdated dependencies: $OUTDATED_DEPENDENCIES"
        "$BOOTSTRAP" "$OUTDATED_DEPENDENCIES"
    else
        echo "Cartfile.resolved matches cached, skipping bootstrap"
    fi
else
    echo "Cached Cartfile.resolved not found, bootstrapping all dependencies"
    "$BOOTSTRAP"
fi

cp Cartfile.resolved Carthage