name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Cache Mint
      uses: actions/cache@v2
      with:
        key: mint_deps
        path: ~/mint
    - uses: actions/checkout@v2
    - name: Install Dependencies
      env:
        MINT_PATH: '~/mint'
      run: |
        brew install mint
        mint bootstrap
    - name: SwiftLint
      env:
        MINT_PATH: '~/mint'
      run: make lint-check
    - name: Run tests
      env:
        LC_CTYPE: 'en_US.UTF-8'
        LANG: 'en_US.UTF-8'
        FRAMEWORK_NAME: 'SwiftRex'
        MINT_PATH: '~/mint'
      run: |
        make test
        make code-coverage-summary
        make code-coverage-file
        bash <(curl -s https://codecov.io/bash) -X xcodellvm -X gcov -f coverage.txt
